### PR TITLE
Allow custom bind address for local dev server

### LINKED ISSUE #596: Specify bind address for local dev server
A custom port can be specified when running the local development server. I couldn't find anything in the docs about being able to specify a custom bind address (i.e `--host 0.0.0.0`). Is this possible? Would be happy to provide a PR if it's not.

### PR DESCRIPTION
**Pull request by BigChief45**
Closes #596 

cc @joguSD

### CODE REVIEW

**Comment by BigChief45** [comment]
@jamesls @joguSD Would appreciate a review or some feedback.

**Comment by jamesls** [comment]
Thanks for the pull request.  Looks like the build is failing, let me see why codecov is complaining.  Otherwise I think this is a reasonable change.

**Comment by jamesls** [comment]
Ahh looks like it's missing a few tests (to be fair they weren't tested prior to this change).  I'll go ahead and get those added before merging.

**Comment by BigChief45** [comment]
Awesome thanks!

**Pull request merged**
