### PR TITLE
Issue #450: Chalice generate-pipeline can create  incompatible yaml

### PR DESCRIPTION
**Pull request by achautha**
If function name in `app.py` contains '_' or special characters,  invalid cloudformation template is created.  We need to remove the special characters before generating cloudformation template.

### CODE REVIEW

**Comment by jamesls** [comment]
Looks good, we just need to get a test added to this before we can merge.

**Comment by achautha** [comment]
@jamesls , thanks for review. I will add a test .

**Comment by jamesls** [comment]
Thanks, looks good.  I made some small changes to the test but otherwise looks good.  Thanks for the pull request!

**Comment by jamesls** [comment]
Merged in https://github.com/aws/chalice/commit/0be9ac866a36a3a17545190ef33f7e8506139874

**Pull request closed without merging**
