### PR TITLE
feature - output cloudfront_zone_id and cloudfront_domain_name in terraform

### PR DESCRIPTION
**Pull request by marcoceppi**
*Issue #, if available:*

*Description of changes:* When using https://aws.github.io/chalice/topics/domainname.html, and terraform packaing, if the api_gateway_custom_domain `cloudfont_zone_id` and `cloudfront_domain_name` aren't provided as outputs, using the generated chalice output as a terraform module won't allow configuring route53 for the domain in question. This exposes those as outputs, similar to `EndpointURL` and `RestAPIId`

I'm uncertain how to generate a new changelog entry, there don't appear to be any documentation on the process or I'd include that as well with this as it is a feature

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jamesls — COMMENTED** [review]
Thanks for the PR.  I think we'd need to add logic for mapping the regional outputs in the case that they're using a regional endpoint, similar to what we do in the `chalice deploy` case.  Then we just need to add tests and this should be good to merge.

**Comment by marcoceppi** [comment]
I'll make those updates and add some tests, thanks!

**Comment by jamesls** [comment]
Oh no worries, it was pretty quick to add so I went ahead and added it.  Once CI passes we should be good to merge.

**Review by jamesls — APPROVED** [review]
CI's good, merging.

**Comment by marcoceppi** [comment]
Thank you! Appreciate that

**Pull request merged**
