### PR TITLE
Return responce from websocket event source handler.

### PR DESCRIPTION
**Pull request by ego**
*WebSocket responce:*

Currently there is no ability to return response from user handler to client via WebSocket.
Especially for `Sec-WebSocket-Protocol` header for `$connect` route.

https://aws.amazon.com/about-aws/whats-new/2020/06/amazon-api-gateway-allows-subprotocols-on-websocket-api-connection/

### CODE REVIEW

**Comment by jamesls** [comment]
Thanks for the pull request.  I'd like to get some tests added before merging, but otherwise looks good.

**Comment by ego** [comment]
> Thanks for the pull request. I'd like to get some tests added before merging, but otherwise looks good.

Added some tests.

**Comment by jamesls** [comment]
Whoops, looks like another PR referenced the wrong PR.  Reopening, thanks for adding tests!

**Comment by jamesls** [comment]
The change looks good, but I noticed that API gateway doesn't forward the body or any additional headers besides the websocket related headers back to the client, so I wonder if people might be expecting those headers to be sent back.  Although the websocket spec is pretty specific about the response it's expecting so I'm not sure what use case someone would have to send back headers besides `Sec-Websocket-Protocol`.

I think I'll just update the docs to state you can return a response but only the `Sec-Websocket-Protocol` header is sent back to the client.

**Review by jamesls — APPROVED** [review]
Everything looks good, looks like all the tests are passing, I'll go ahead and merge.  Thanks for the PR!

**Pull request merged**
