### PR TITLE
Add support for CDK Version 2

### PR DESCRIPTION
**Pull request by knowsuchagency**
*Issue #, if available:*

Addresses #1742 

*Description of changes:*

* updates the `cdk-ddb` template to support cdk version 2
* tested against both cdk version 2 and version 1
* to use cdk version 2: `pip install 'chalice[cdkv2]'`
* documentation has been updated to reflect this change

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by leonelgalan** [comment]
This is great given the recent news: [AWS CDK v1 will enter Maintenance Mode after June 1, 2022 aws/aws-cdk#19836](https://github.com/aws/aws-cdk/issues/19836)

**Comment by jamesls** [comment]
Looks like I spoke too soon.  The way CDK handles assets changed from v1 to v2 so now the functional tests are failing.  I pushed a few changes to this PR branch that also updated the CI to run the CDK tests against v1 and v2.  Once those are updated and passing we can get this merged.


```
    def test_can_package_as_cdk_app(runner):
        # The CDK loading/synth can take a while so we're testing the
        # various APIs out in one test to cut down on test time.
        with runner.isolated_filesystem():
            newproj.create_new_project_skeleton(
                'testcdkpackage', project_type='cdk-ddb')
            dirname = os.path.abspath(os.path.join('testcdkpackage',
                                                   'infrastructure'))
            os.chdir(dirname)
            cdk_app, chalice_app = load_chalice_construct(
                dirname, 'testcdkpackage')
            assembly = cdk_app.synth()
            stack = assembly.get_stack_by_name('testcdkpackage')
            cfn_template = stack.template
            resources = cfn_template['Resources']
            # Sanity check that we have the resources from Chalice as well as the
            # resources from the ChaliceApp construct.
            assert 'APIHandler' in resources
            assert 'DefaultRole' in resources
            ddb_tables = filter_resources(cfn_template, 'AWS::DynamoDB::Table')[0]
            # CDK adds a random suffix to our resource name so we verify that
            # the name starts with our provided name "AppTable".
            assert ddb_tables[0].startswith('AppTable')
            # We also need to verify that we've replaces the CodUri with the
            # CDK specific assets.
            functions = filter_resources(
                cfn_template, 'AWS::Serverless::Function')[0]
>           bucket_ref = functions[1]['Properties']['CodeUri']['Bucket']['Ref']
E           KeyError: 'Ref'

tests/functional/cdk/test_construct.py:89: KeyError
```

**Comment by knowsuchagency** [comment]
Thanks @jamesls is that something you might be able to do? To be honest, I'm not currently using chalice; it just seemed like a relatively straightforward fix when I was looking at the project. I'm pretty busy in the coming weeks so getting the tests to pass isn't something I'm likely to have time for.

**Comment by jamesls** [comment]
> Thanks @jamesls is that something you might be able to do? To be honest, I'm not currently using chalice; it just seemed like a relatively straightforward fix when I was looking at the project. I'm pretty busy in the coming weeks so getting the tests to pass isn't something I'm likely to have time for.

Yeah no problem, I can take it from here.  Thanks for your work on this!

**Comment by knowsuchagency** [comment]
Thanks @jamesls :)

**Pull request merged**
