### PR TITLE
delete cloud watch rule

### PR DESCRIPTION
**Pull request by achautha**
Fixes issue #535

### CODE REVIEW

**Comment by achautha** [comment]
@stealthycoin , Build is in pending state for long time. Could you please help ?

**Comment by jamesls** [comment]
Thanks for the pull request.  I restarted the build and looks like travis went through.

I believe codecov is complaining because there's test for the new API call to `delete_rule`, but no updated tests for the deployer module changes.  Could you add a test for the deployer changes (to `tests/unit/deploy/test_deploy.py`)?

**Comment by achautha** [comment]
Sure @jamesls . I will add test cases for deployer code.

**Comment by achautha** [comment]
@jamesls Added new case as per your recommendation. Coverage is passing now. Thanks for review.

**Pull request merged**
