### PR TITLE
xray active config support

### PR DESCRIPTION
**Pull request by kapilt**
Addresses #464

Expose xray configuration property to setup X-ray Active Tracing Config.

Couple of thoughts on exploring fuller integration.

- [ ] propagating trace headers
- [x] attaching managed policy (xraywrite) to managed roles
- [ ] chalice new-project taking an xray flag to configure the xray sdk.
- [x] turning on xray for the Api Gateway stage (tracingEnabled)
- [ ] take an optional dependency on xray sdk and auto setup and sdk subscribers ala segments/subsegments (akin to https://github.com/aws/aws-xray-sdk-python/pull/66)

### CODE REVIEW

**Comment by haidaraM** [comment]
Any news on this :-) ?

**Comment by Ph4rell** [comment]
Any news on this :-) ?

**Comment by jamesls** [comment]
Picking up this work again.  I think that this combined with the chalice middleware feature would be sufficient as a first pass at supporting xray.  I'll also see if it makes sense to contribute chalice middleware directly to the xray SDK.

**Review by jamesls — APPROVED** [review]
Rebased from master and added terraform template support.  I think this change looks good assuming travis passes.

**Pull request merged**
