### PR TITLE
Added MaximumBatchingWindowInSeconds #1778

### PR DESCRIPTION
**Pull request by kmbotts**
*Issue #, if available:*
#1778 

*Description of changes:*
Added MaximumBatchingWindowInSeconds to Stream (Kinesis, DynamoDb) and SQS handlers (defaulting to zero seconds). Updated necessary classes and along with Terrformform/Cloudformation generation scripts and all accompanying tests. Added new tests to validate setting of new attribute.

I have not updated documentation, but can once we have settled on the naming convention of the new field. I chose the verbose version so that it aligns with other documentation (AWS and Terraform).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by kmbotts** [comment]
I already see an issue with line length. namely due to the new attribute name. Suggestions are welcome
```
chalice/package.py:648:80: E501 line too long (98 > 79 characters)

**Comment by kmbotts** [comment]
Updated documentation

**Comment by jamesls** [comment]
Thanks for the PR looking over this now.  I'll go ahead and fix up the line length issues so we can get the rest of the tests running on the GH action.

**Comment by jamesls** [comment]
Looks like the `awsclient.py` needs to be updated for the `chalice deploy` case.  When I try this out I get:

```
Traceback (most recent call last):
  File "chalice/chalice/cli/__init__.py", line 636, in main
    return cli(obj={})
  File ".virtualenvs/chalice-39/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File ".virtualenvs/chalice-39/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File ".virtualenvs/chalice-39/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".virtualenvs/chalice-39/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".virtualenvs/chalice-39/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File ".virtualenvs/chalice-39/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "chalice/chalice/cli/__init__.py", line 189, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "chalice/chalice/deploy/deployer.py", line 376, in deploy
    return self._deploy(config, chalice_stage_name)
  File "chalice/chalice/deploy/deployer.py", line 392, in _deploy
    self._executor.execute(plan)
  File "chalice/chalice/deploy/executor.py", line 42, in execute
    getattr(self, '_do_%s' % instruction.__class__.__name__.lower(),
  File "chalice/chalice/deploy/executor.py", line 55, in _do_apicall
    result = method(**final_kwargs)
TypeError: create_lambda_event_source() got an unexpected keyword argument 'maximum_batching_window_in_seconds'
```

Specifically:

```
    def create_lambda_event_source(self, event_source_arn, function_name,
                                   batch_size, starting_position=None):
        # type: (str, str, int, Optional[str]) -> None
        lambda_client = self._client('lambda')
```

Just a heads up, I rebased/push a few changes that fix the line length issues so we can get the CI tests running against this PR.

**Comment by kmbotts** [comment]
Thanks for the heads up. I was able to reset my branch and I see your changes. I'll give this other issue a look once I have the chance.

**Comment by kmbotts** [comment]
Pushed some changes to the create/update lambda event source in awsclient.py to handle the new argument. updated and added a couple tests as well.

**Review by jamesls — APPROVED** [review]
Nice, looks good to me.  Thanks for the PR!

**Comment by jamesls** [comment]
Merged in 2576536c

**Pull request closed without merging**
