### PR TITLE
Add before_response and after_response decorators

### PR DESCRIPTION
**Pull request by kislyuk**
@jamesls, I'm wondering if this is something you would be open to copying from Flask, I find myself needing these a lot.

If you're open to this in principle, I can add tests and docs.

### CODE REVIEW

**Comment by jamesls** [comment]
I'm certainly open to this feature.  I think this could be really useful.

I always like hearing a few concrete use cases.  Would you mind sharing some of the specific things this would help you with?

**Comment by kislyuk** [comment]
I use it for code that is shared between all or many routes: authentication/authorization (without API Gateway custom authenticators, which are complex to set up and seem to add latency), common parameter/header parsing and erroring, logging, etc. It can also be useful for some types of rate limiting/backpressure, etc.

**Comment by jmehnle** [comment]
@jamesls, between this and #719, what are your thoughts?

**Comment by jamesls** [comment]
Closing out old PR, superceded via https://github.com/aws/chalice/pull/1514

**Pull request closed without merging**
